version: '3'
#Docker Networks
networks:
  app-network: null
services:
  #Nginx Service
  nginx:
    image: 'nginx:stable-alpine'
    container_name: 'nginx_${APP_NAME}'
    ports:
      - "80:80"
    volumes: 
      - './dist:/var/www/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - app-network
  npm:
    image: 'node:13.7'
    container_name: 'npm_${APP_NAME}'
    volumes: 
      - './:/var/www/html'
    working_dir: /var/www/html
    entrypoint: 
      - npm